version: "3.3"

services: 
  c-carta:
    labels: 
      - "traefik.http.routers.c-carta.rule=Host(`c-carta.restoner-api.fun`)"
    restart: always 
    build: .
    networks:
      - traefik_net
    links:
      - postgres-master
  postgres-master:
    container_name: postgres_db
    restart: always
    image: "bitnami/postgresql:14"
    networks:
      - traefik_net
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    ports:
      - "5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - DATABASE_HOST=127.0.0.1
      - POSTGRESQL_REPLICATION_USER=replicacion_wdsg346wefwerfusuario_123
      - POSTGRESQL_REPLICATION_PASSWORD=replicacion_contrasengq234qdia_123
      - POSTGRESQL_USERNAME=postgresx4y
      - POSTGRESQL_PASSWORD=asd34Fg2DDFfd3saF3Fgge65sGGS45
      - POSTGRESQL_DATABASE=postgresx4y
  postgresql-slave:
    image: 'bitnami/postgresql:14'
    ports:
      - "6432:5432"
    networks:
      - traefik_net
    depends_on:
      - postgres-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicacion_wdsg346wefwerfusuario_123
      - POSTGRESQL_REPLICATION_PASSWORD=replicacion_contrasengq234qdia_123
      - POSTGRESQL_MASTER_HOST=postgres-master
      - POSTGRESQL_PASSWORD=asd34Fg2DDFfd3saF3Fgge65sGGS45
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
  pgadmin:
    restart: always
    image: "dpage/pgadmin4"
    networks:
      - traefik_net
    ports:
      - "90:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: adminxd4@adminxd4.com
      PGADMIN_DEFAULT_PASSWORD: asd34Fg2Dsaf53543Fgge65sGGS45
    depends_on:
      - postgres-master
  traefik:
    image: traefik:v2.3.6
    ports: 
      - 80:80
    networks:
      - traefik_net
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
  mongo:
    image: mongo
    restart: always
    networks:
      - traefik_net
    ports:
      - "27017:27017"
    volumes: 
      - shared_database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mo5345ngodbinvenhs56752
      MONGO_INITDB_ROOT_PASSWORD: mongwet2354rghs25oty41
  mongo-express:
    image: "mongo-express:1.0.0-alpha.4"
    restart: always
    ports:
      - "91:8081"
    networks:
      - traefik_net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mo5345ngodbinvenhs56752
      ME_CONFIG_MONGODB_ADMINPASSWORD: adgadsfg234GWe5Ggwf34G52fag3
      ME_CONFIG_BASICAUTH_USERNAME: mongobasicaerw3uthfw26666
      ME_CONFIG_BASICAUTH_PASSWORD: dasd23GG332165eeFa435fuj6c
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_URL: mongodb://mo5345ngodbinvenhs56752:mongwet2354rghs25oty41@mongo:27017/
networks:
  traefik_net:
    name: traefik_n
    driver: bridge
    ipam: 
      driver: default 
volumes:
  postgresql_master_data:
  shared_database:






