version: "3.3"

services: 
  c-carta:
    labels: 
      - "traefik.http.routers.c-carta.rule=Host(`c-carta.restoner-api.fun`)"
    restart: always 
    build: .
    networks:
      - traefik_network
    links:
      - postgres
  postgres:
    container_name: postgres_db
    restart: always
    image: "postgres:13"
    networks:
      - traefik_network
    ports:
      - "7000:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgresx4y
      - POSTGRES_PASSWORD=asd34Fg2DDFfd3saF3Fgge65sGGS45
      - POSTGRES_DB=postgresx4y
  pgadmin:
    restart: always
    image: "dpage/pgadmin4"
    networks:
      - traefik_network
    ports:
      - "90:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: adminxd4@adminxd4.com
      PGADMIN_DEFAULT_PASSWORD: asd34Fg2Dsaf53543Fgge65sGGS45
    depends_on:
      - postgres
  traefik:
    image: traefik:v2.3.6
    ports: 
      - 80:80
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
  mongo:
    image: mongo
    restart: always
    networks:
      - traefik_network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mo5345ngodbinvenhs56752
      MONGO_INITDB_ROOT_PASSWORD: mongwet2354rghs25oty41
  mongo-express:
    image: "mongo-express:1.0.0-alpha.4"
    restart: always
    ports:
      - "91:8081"
    networks:
      - traefik_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mo5345ngodbinvenhs56752
      ME_CONFIG_MONGODB_ADMINPASSWORD: adgadsfg234GWe5Ggwf34G52fag3
      ME_CONFIG_BASICAUTH_USERNAME: mongobasicaerw3uthfw26666
      ME_CONFIG_BASICAUTH_PASSWORD: dasd23GG332165eeFa435fuj6c
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_URL: mongodb://mo5345ngodbinvenhs56752:mongwet2354rghs25oty41@mongo:27017/
networks:
  traefik_network:
    name: traefik_net
    driver: bridge
    ipam: 
      driver: default 








