api:
  insecure: true

entrypoints:
  web:
    address: ":80"
  websecurity:
    address: ":443"
    
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    
  file:
    filename: /config.yml